# Generated by Django 5.2.17 on 2026-08-16 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ban_reason_user_banned_at_user_banned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_ban_reason',
            field=models.TextField(blank=True, help_text='Reason for challenge ban'),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_banned',
            field=models.BooleanField(default=False, help_text='Ban user from daily challenges'),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_banned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who banned user from challenges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_banned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
