# Generated by Django 5.2.17 on 2026-08-16 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewsession_candidateresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('camera_off', 'Camera Turned Off'), ('screen_share_lost', 'Screen Share Lost'), ('multiple_windows', 'Multiple Windows Detected'), ('tab_switch', 'Tab Switch Detected'), ('window_blur', 'Window Lost Focus'), ('copy_paste', 'Copy/Paste Attempt'), ('external_device', 'External Device/Phone Detected'), ('rapid_responses', 'Suspiciously Rapid Responses'), ('no_audio', 'No Audio/Microphone Input'), ('unusual_pattern', 'Unusual Answer Pattern')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('suspended', 'Session Suspended'), ('banned', 'Account Banned')], default='none', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['candidate', '-detected_at'], name='interviews__candida_935120_idx'), models.Index(fields=['session', 'severity'], name='interviews__session_ed584c_idx')],
            },
        ),
    ]
