# Generated by Django 5.2.17 on 2026-08-16 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_suspiciousactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='activity_type',
            field=models.CharField(choices=[('camera_off', 'Camera Turned Off'), ('screen_share_lost', 'Screen Share Lost'), ('multiple_windows', 'Multiple Windows Detected'), ('tab_switch', 'Tab Switch Detected'), ('window_blur', 'Window Lost Focus'), ('copy_paste', 'Copy/Paste Attempt'), ('external_device', 'External Device/Phone Detected'), ('rapid_responses', 'Suspiciously Rapid Responses'), ('no_audio', 'No Audio/Microphone Input'), ('unusual_pattern', 'Unusual Answer Pattern'), ('fullscreen_exit', 'Exited Full-Screen Mode'), ('screen_share_disabled', 'Screen Share Stopped or Denied')], max_length=50),
        ),
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(blank=True)),
                ('expected_keywords', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='interviews.codingchallenge')),
            ],
            options={
                'ordering': ['-score', '-submitted_at'],
            },
        ),
    ]
