# Generated by Django 5.2.17 on 2026-08-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_suspiciousactivity_activity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_submission_date', models.DateField(blank=True, null=True)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_streak', '-best_score'],
            },
        ),
    ]
