# Generated by Django 5.2.17 on 2026-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_challengestreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='copy_paste_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='copy_paste_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='execution_result',
            field=models.JSONField(default=dict, help_text='Stores test results and execution data'),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codingchallenge',
            name='test_cases',
            field=models.JSONField(default=list, help_text='List of {"input": "", "output": ""} objects'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('rust', 'Rust')], default='python', max_length=20),
        ),
    ]
