# Generated by Django 5.2.17 on 2026-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_challengesubmission_copy_paste_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingchallenge',
            name='timer_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Time limit in minutes'),
        ),
    ]
