# Generated by Django 5.2.17 on 2026-08-16 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_codingchallenge_timer_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date for this rotation', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenge_rotations', to=settings.AUTH_USER_MODEL)),
                ('easy_challenge', models.ForeignKey(blank=True, help_text='Easy difficulty challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_easy', to='interviews.codingchallenge')),
                ('hard_challenge', models.ForeignKey(blank=True, help_text='Hard difficulty challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_hard', to='interviews.codingchallenge')),
                ('medium_challenge', models.ForeignKey(blank=True, help_text='Medium difficulty challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_medium', to='interviews.codingchallenge')),
            ],
            options={
                'verbose_name': 'Daily Challenge Rotation',
                'verbose_name_plural': 'Daily Challenge Rotations',
                'ordering': ['-date'],
            },
        ),
    ]
