# Generated by Django 5.2.17 on 2026-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_dailychallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychallenge',
            name='easy_challenge',
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='hard_challenge',
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='medium_challenge',
        ),
        migrations.AddField(
            model_name='codingchallenge',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after the user answers'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='challenges',
            field=models.ManyToManyField(help_text='Challenges for the day', related_name='daily_rotations', to='interviews.codingchallenge'),
        ),
    ]
